import { Task } from '@/types'

export const seedTasks: Task[] = [
  {
    id: 'seed-1',
    title: 'Morning routine',
    notes: null,
    category: 'health',
    priority: 'high',
    subtasks: [
      { id: 'seed-1-a', title: 'Make the bed', completed: false },
      { id: 'seed-1-b', title: 'Drink water', completed: false },
      { id: 'seed-1-c', title: 'Brush teeth', completed: false },
    ],
    timeStart: '06:00',
    timeEnd: '06:30',
    repeat: { type: 'daily' },
    createdAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: 'seed-2',
    title: 'Stretching',
    notes: null,
    category: 'health',
    priority: 'medium',
    subtasks: [
      { id: 'seed-2-a', title: 'Neck stretch', completed: false },
      { id: 'seed-2-b', title: 'Shoulder rolls', completed: false },
      { id: 'seed-2-c', title: 'Hamstrings', completed: false },
    ],
    timeStart: '06:30',
    timeEnd: null,
    repeat: { type: 'daily' },
    createdAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: 'seed-3',
    title: 'Review priorities',
    notes: 'What are the 3 most important things today?',
    category: 'work',
    priority: 'high',
    subtasks: [],
    timeStart: '07:00',
    timeEnd: null,
    repeat: { type: 'daily' },
    createdAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: 'seed-4',
    title: 'Workout',
    notes: null,
    category: 'health',
    priority: 'medium',
    subtasks: [],
    timeStart: '07:30',
    timeEnd: '08:30',
    repeat: { type: 'weekdays' },
    createdAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: 'seed-5',
    title: 'Stay hydrated',
    notes: 'Aim for 8 glasses throughout the day.',
    category: 'health',
    priority: 'low',
    subtasks: [],
    timeStart: null,
    timeEnd: null,
    repeat: { type: 'daily' },
    createdAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: 'seed-6',
    title: 'Wind down & sleep',
    notes: null,
    category: 'health',
    priority: 'medium',
    subtasks: [],
    timeStart: '22:00',
    timeEnd: null,
    repeat: { type: 'daily' },
    createdAt: new Date().toISOString(),
    isActive: true,
  },
]
