import { Task } from '@/types'

export const seedTasks: Task[] = [
  // ─── HEALTH ───────────────────────────────────────────────
  {
    id: 'seed-1',
    title: 'Morning Routine',
    notes: 'How you start your morning sets the tone for the whole day.',
    category: 'health',
    priority: 'high',
    subtasks: [
      { id: 'seed-1-a', title: 'Make the bed', completed: false },
      { id: 'seed-1-b', title: 'Drink a glass of water', completed: false },
      { id: 'seed-1-c', title: '5-min stretch', completed: false },
      { id: 'seed-1-d', title: 'Cold shower', completed: false },
    ],
    timeStart: '06:00',
    timeEnd: '06:30',
    repeat: { type: 'daily' },
    createdAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: 'seed-2',
    title: 'Push Day',
    notes: 'Chest, shoulders, triceps. Rest 60–90s between sets.',
    category: 'health',
    priority: 'medium',
    subtasks: [
      { id: 'seed-2-a', title: 'Bench press — 4×8', completed: false },
      { id: 'seed-2-b', title: 'Overhead press — 3×10', completed: false },
      { id: 'seed-2-c', title: 'Incline dumbbell press — 3×12', completed: false },
      { id: 'seed-2-d', title: 'Tricep dips — 3×15', completed: false },
    ],
    timeStart: '07:00',
    timeEnd: '08:00',
    repeat: { type: 'custom', days: [1] }, // Monday
    createdAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: 'seed-3',
    title: 'Pull Day',
    notes: 'Back, biceps, rear delts. Focus on controlled reps.',
    category: 'health',
    priority: 'medium',
    subtasks: [
      { id: 'seed-3-a', title: 'Pull-ups — 4×8', completed: false },
      { id: 'seed-3-b', title: 'Barbell rows — 3×10', completed: false },
      { id: 'seed-3-c', title: 'Lat pulldown — 3×12', completed: false },
      { id: 'seed-3-d', title: 'Bicep curls — 3×15', completed: false },
    ],
    timeStart: '07:00',
    timeEnd: '08:00',
    repeat: { type: 'custom', days: [3] }, // Wednesday
    createdAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: 'seed-4',
    title: 'Leg Day',
    notes: "Don't skip leg day.",
    category: 'health',
    priority: 'medium',
    subtasks: [
      { id: 'seed-4-a', title: 'Squats — 4×8', completed: false },
      { id: 'seed-4-b', title: 'Romanian deadlift — 3×10', completed: false },
      { id: 'seed-4-c', title: 'Leg press — 3×12', completed: false },
      { id: 'seed-4-d', title: 'Calf raises — 4×20', completed: false },
    ],
    timeStart: '07:00',
    timeEnd: '08:00',
    repeat: { type: 'custom', days: [5] }, // Friday
    createdAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: 'seed-5',
    title: 'Cardio',
    notes: 'Active recovery. Keep heart rate at 120–140 bpm.',
    category: 'health',
    priority: 'low',
    subtasks: [
      { id: 'seed-5-a', title: '5-min warm-up walk', completed: false },
      { id: 'seed-5-b', title: '30-min jog or bike', completed: false },
      { id: 'seed-5-c', title: '5-min cool-down stretch', completed: false },
    ],
    timeStart: '07:30',
    timeEnd: '08:15',
    repeat: { type: 'custom', days: [0] }, // Sunday
    createdAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: 'seed-6',
    title: 'Stay Hydrated',
    notes: 'Aim for 8 glasses throughout the day. A full bottle on your desk helps.',
    category: 'health',
    priority: 'low',
    subtasks: [],
    timeStart: null,
    timeEnd: null,
    repeat: { type: 'daily' },
    createdAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: 'seed-7',
    title: 'Wind Down',
    notes: 'Signal to your brain that the day is over. Consistency matters more than perfection.',
    category: 'health',
    priority: 'medium',
    subtasks: [
      { id: 'seed-7-a', title: 'No screens 30 min before bed', completed: false },
      { id: 'seed-7-b', title: 'Write 3 things you did well today', completed: false },
      { id: 'seed-7-c', title: 'Lights off', completed: false },
    ],
    timeStart: '22:00',
    timeEnd: null,
    repeat: { type: 'daily' },
    createdAt: new Date().toISOString(),
    isActive: true,
  },

  // ─── WORK ─────────────────────────────────────────────────
  {
    id: 'seed-8',
    title: 'Plan My Day',
    notes: "Decide what winning looks like today before the day decides for you.",
    category: 'work',
    priority: 'high',
    subtasks: [
      { id: 'seed-8-a', title: 'Review calendar & meetings', completed: false },
      { id: 'seed-8-b', title: 'Set top 3 priorities', completed: false },
      { id: 'seed-8-c', title: 'Clear inbox to zero', completed: false },
    ],
    timeStart: '08:00',
    timeEnd: '08:15',
    repeat: { type: 'weekdays' },
    createdAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: 'seed-9',
    title: 'Deep Work',
    notes: 'Protect this block. No Slack, no email, no meetings.',
    category: 'work',
    priority: 'high',
    subtasks: [
      { id: 'seed-9-a', title: 'Turn off notifications', completed: false },
      { id: 'seed-9-b', title: 'Work on priority #1', completed: false },
      { id: 'seed-9-c', title: 'Quick progress check at end', completed: false },
    ],
    timeStart: '09:00',
    timeEnd: '11:00',
    repeat: { type: 'weekdays' },
    createdAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: 'seed-10',
    title: 'End of Day Wrap-up',
    notes: 'Leave tomorrow a gift — a clear desk and a clear head.',
    category: 'work',
    priority: 'medium',
    subtasks: [
      { id: 'seed-10-a', title: "Update today's task list", completed: false },
      { id: 'seed-10-b', title: "Set tomorrow's top 3", completed: false },
      { id: 'seed-10-c', title: 'Reply to pending messages', completed: false },
      { id: 'seed-10-d', title: 'Tidy desk', completed: false },
    ],
    timeStart: '17:00',
    timeEnd: '17:15',
    repeat: { type: 'weekdays' },
    createdAt: new Date().toISOString(),
    isActive: true,
  },

  // ─── FUN ──────────────────────────────────────────────────
  {
    id: 'seed-11',
    title: 'Read',
    notes: '20 pages a day is 7,000 pages a year — about 20 books.',
    category: 'fun',
    priority: 'medium',
    subtasks: [],
    timeStart: '21:00',
    timeEnd: '21:30',
    repeat: { type: 'daily' },
    createdAt: new Date().toISOString(),
    isActive: true,
  },
]
